vich_uploader:
    db_driver: orm

    mappings:
        project_file:
            uri_prefix: /project
            upload_destination: '%upload_directory%'
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
